services:
  php: 
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: yii2-php
    volumes:
      - ../edrn/:/var/www/edrn
  nginx:
    image: nginx:latest
    container_name: yii2-nginx
    ports:
      - "8080:80"
    volumes:
      - ../edrn:/var/www/edrn
      - ./conf.d:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
  postgres:
    image: postgres:latest
    container_name: yii2-postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=edrn
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    container_name: yii2-redis
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

